### ISSUE TITLE
is there feature for streal realtime new feature on aistudio already available on python

### ISSUE THREAD

**Issue by vizvasrj** [googleapis/go-genai#14]
here is python cookbook which i can use it but is there any go sdk for this ?
https://github.com/google-gemini/cookbook/blob/main/gemini-2/live_api_starter.py
thank you
i think its this but its seens not working 
https://github.com/googleapis/go-genai/blob/86542a270d3ea4813220af40e5bf0aab62d60008/samples/generate_audio.go

**Comment by qiaodev** [comment]
@vizvasrj What's the error message you got from https://github.com/googleapis/go-genai/blob/86542a270d3ea4813220af40e5bf0aab62d60008/samples/generate_audio.go

Thanks

**Comment by vizvasrj** [comment]
I solved it now there is no issue? i think that was not i looking for

**Comment by vizvasrj** [comment]
i was looking for like stream realtime for genai i can use it via python, its cool, and i like to know is there any go sdk for that or if where i can find doc to create it?

**Comment by qiaodev** [comment]
Thanks. We're working on adding real-time streaming and hope to have it ready soon.
