### ISSUE TITLE
Don't introduce too many helper types for input and output

### ISSUE THREAD

**Issue by rakyll** [googleapis/go-genai#5]
The current API surface is extremely confusing for `GenerateContent` because it introduces a wide range of indirection with helper types such as:

```
- Contents
- Texts
- PartSlice
- ContentSlice
```

As a user, it's hard for me to understand what's actually supported here without reading the library implementation. Remove all of these types and stick to []Content as inputs and outputs.  The following code isn't very hard to write:

```
GenerateContentStream(ctx, "model", []genai.Content{{Parts: parts}}, nil)
```

The helper types don't help the average Go user because we like orthogonality and less magic. A little bit verbosity is ok to remove indirection.

**Comment by qiaodev** [comment]
Thanks for the feedback.  I'd also like to hear what @eliben and @jba think.

**Comment by qiaodev** [comment]
GenerateContentStream(ctx, "model", []genai.Content{{Parts: parts}}, nil)
GenerateContentStream(ctx, "model", genai.Text("hello").ToContents(), nil)

We can support both. @rakyll What do you think?

**Comment by jba** [comment]
Is there any `Content` that's not a list of `Part`s?
In github.com/google/generative-ai-go/genai, we just use a `[]Part`. What can you do with this API that you can't with that?

**Comment by qiaodev** [comment]
There is Role field in the Content. If we use []Part, how to pass the Role field in? And how to ensure future proof.

**Comment by jba** [comment]
OK. That isn't really clear from the doc. For example, here is the doc for Text:
![image](https://github.com/user-attachments/assets/11ec631e-b336-4426-999b-726e0bd7a4e8)
I wouldn't guess from that that I can only use Text for the user role. If I'm doing a session and want to send a model response back to the model (roleModel), it would be wrong to use Text.

Separately from that, would it simplify things if the argument to GenerateContent was []Content, and you got rid of the XXXSlice types?

**Comment by qiaodev** [comment]
https://pkg.go.dev/google.golang.org/genai#Models.GenerateContent

func (m [Models](https://pkg.go.dev/google.golang.org/genai#Models)) GenerateContent(ctx [context](https://pkg.go.dev/context).[Context](https://pkg.go.dev/context#Context), model [string](https://pkg.go.dev/builtin#string), contents []*[Content](https://pkg.go.dev/google.golang.org/genai#Content), config *[GenerateContentConfig](https://pkg.go.dev/google.golang.org/genai#GenerateContentConfig)) (*[GenerateContentResponse](https://pkg.go.dev/google.golang.org/genai#GenerateContentResponse), [error](https://pkg.go.dev/builtin#error))

We have changed the API surface change to []*Content type.
