### ISSUE TITLE
Add a link to godoc from README

### ISSUE THREAD

**Issue by rakyll** [googleapis/go-genai#6]
It's conventional for Go packages to add a godoc badge on their READMEs.

You can use the package site badge creator, https://pkg.go.dev/badge/:

```
[![Go Reference](https://pkg.go.dev/badge/google.golang.org/genai.svg)](https://pkg.go.dev/google.golang.org/genai)
```

**Comment by jscud** [comment]
Great suggestion, we'll add this.

**Comment by qiaodev** [comment]
reference link added
