### ISSUE TITLE
Rename IncludeRaiReason to IncludeRAIReason

### ISSUE THREAD

**Issue by rakyll** [googleapis/go-genai#7]
Per initialism conventions in Go, RAI should be all capital. Due to autogeneration, `IncludeRaiReason` isn't following this convention.

**Comment by jscud** [comment]
Great suggestion! As is the case for https://github.com/googleapis/go-genai/issues/8, we'll discuss this proposal and respond back.

**Comment by jscud** [comment]
Completed, thanks for raising this issue.
