### ISSUE TITLE
Rename FinishReasonSpii to FinishReasonSPII

### ISSUE THREAD

**Issue by rakyll** [googleapis/go-genai#9]
Per initialism conventions in Go, `FinishReasonSpii` should be `FinishReasonSPII`.

See https://go.dev/wiki/CodeReviewComments#initialisms for more.

**Comment by jscud** [comment]
Great suggestion! As is the case for https://github.com/googleapis/go-genai/issues/8, we'll discuss this proposal and respond back.

**Comment by jscud** [comment]
Completed, thanks for raising this issue.
